# Generated by Django 4.1.4 on 2022-12-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convert',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='convert',
            name='yt_url',
            field=models.CharField(max_length=200, verbose_name='Youtube link'),
        ),
    ]
